spring:
  jpa:
    open-in-view: true
  messages:
    basename: messages, errors
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  servlet:
    session:
      tracking-modes: cookie

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/tumblbug
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

file:
  dir: file

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/tumblbug
    username: admin
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

file:
  dir: file